# Generated by Django 2.1.7 on 2019-07-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_List_Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Single_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Year', models.IntegerField()),
                ('Points', models.IntegerField()),
                ('Assits', models.IntegerField()),
                ('Rebounds', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Games', models.IntegerField()),
                ('Minutes', models.FloatField()),
                ('Field_Goals_attempted', models.IntegerField()),
                ('Field_Goal_percentage', models.FloatField()),
                ('ThreeP_attempted', models.IntegerField()),
                ('ThreeP_percentage', models.FloatField()),
                ('Offensive_rebounds', models.IntegerField()),
                ('Total_rebounds', models.IntegerField()),
                ('Eff_FGP', models.FloatField()),
                ('Free_throws', models.IntegerField()),
                ('Free_throw_percentage', models.FloatField()),
                ('Steals', models.IntegerField()),
                ('Blocks', models.IntegerField()),
                ('Turnovers', models.IntegerField()),
                ('Fouls', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='master_list_players',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NBA_Stats.Single_Player'),
        ),
    ]
