# Generated by Django 2.1.7 on 2019-07-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_player',
            name='Assits',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='single_player',
            name='Points',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='single_player',
            name='Rebounds',
            field=models.FloatField(),
        ),
    ]
