# Generated by Django 2.1.7 on 2019-07-20 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0002_auto_20190719_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_player',
            name='Total_rebounds',
        ),
    ]
