# Generated by Django 2.1.7 on 2019-07-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0003_remove_single_player_total_rebounds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='single_player',
            old_name='Assits',
            new_name='Assists',
        ),
    ]
