# Generated by Django 2.1.7 on 2019-07-20 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0004_auto_20190719_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Player_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Year', models.IntegerField()),
                ('Points', models.FloatField()),
                ('Assists', models.FloatField()),
                ('Rebounds', models.FloatField()),
                ('Age', models.IntegerField()),
                ('Games', models.IntegerField()),
                ('Minutes', models.FloatField()),
                ('Field_Goals_attempted', models.IntegerField()),
                ('Field_Goal_percentage', models.FloatField()),
                ('ThreeP_attempted', models.IntegerField()),
                ('ThreeP_percentage', models.FloatField()),
                ('Offensive_rebounds', models.IntegerField()),
                ('Eff_FGP', models.FloatField()),
                ('Free_throws', models.IntegerField()),
                ('Free_throw_percentage', models.FloatField()),
                ('Steals', models.IntegerField()),
                ('Blocks', models.IntegerField()),
                ('Turnovers', models.IntegerField()),
                ('Fouls', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Assists',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Blocks',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Eff_FGP',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Field_Goal_percentage',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Field_Goals_attempted',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Fouls',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Free_throw_percentage',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Free_throws',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Games',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Minutes',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Offensive_rebounds',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Points',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Rebounds',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Steals',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='ThreeP_attempted',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='ThreeP_percentage',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Turnovers',
        ),
        migrations.RemoveField(
            model_name='single_player',
            name='Year',
        ),
        migrations.AlterField(
            model_name='master_list_players',
            name='Player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Single_Player'),
        ),
        migrations.AlterField(
            model_name='single_player',
            name='Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='single_player',
            name='Season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Single_Player_Year'),
        ),
    ]
