# Generated by Django 2.1.7 on 2019-07-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0005_auto_20190719_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_player',
            name='Year',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='single_player',
            name='Name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
