# Generated by Django 2.1.7 on 2019-07-20 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0007_auto_20190720_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_player_year',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Single_Player'),
        ),
    ]
