# Generated by Django 2.1.7 on 2019-07-21 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0009_auto_20190720_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=60)),
                ('Year', models.IntegerField(default=None)),
                ('All_Star', models.BooleanField(default=None)),
                ('All_NBA', models.IntegerField(blank=True)),
                ('All_NBA_defense', models.IntegerField(blank=True)),
                ('MVP', models.BooleanField(default=False)),
                ('DPOY', models.BooleanField(default=False)),
                ('MIP', models.BooleanField(default=False)),
                ('All_Rookie', models.IntegerField(blank=True)),
                ('Champion', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='advanced_stats',
            name='Name_Year',
        ),
        migrations.RemoveField(
            model_name='basic_stats',
            name='Name_Year',
        ),
        migrations.RemoveField(
            model_name='single_season',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='single_season',
            name='Year',
        ),
        migrations.AddField(
            model_name='advanced_stats',
            name='Name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='advanced_stats',
            name='Year',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='basic_stats',
            name='Name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='basic_stats',
            name='Year',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='single_season',
            name='Advanced_Stats',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Advanced_Stats'),
        ),
        migrations.AddField(
            model_name='single_season',
            name='Basic_Stats',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Basic_Stats'),
        ),
        migrations.AddField(
            model_name='single_season',
            name='Awards',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='NBA_Stats.Awards'),
        ),
    ]
