# Generated by Django 2.1.7 on 2019-07-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NBA_Stats', '0010_auto_20190720_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='single_season',
            name='Awards',
        ),
    ]
